name: Action Demo
on: [push]
jobs:
  demo-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "single comment"
      - name: Just the name of the step that you really wants to use
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
